version: '3.8'

services:
  wordpress-cf-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3333:3000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/var/www/frontend.community.cyberjake.xyz/public:ro
    ports:
      - "8080:80"